image: archlinux
packages:
  - emacs-nox
sources:
  - https://git.sr.ht/~thecatster/spotsync
secrets:
  - 3ec8d6c4-470d-4198-8b1c-b3c772f8fff3
tasks:
  - mirror: |
      cd spotsync
      git remote add github git@github.com:thecatster/spotsync
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git push -f github master
